# Generated by Django 6.0 on 2025-12-19 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_knowledgedocument_external_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="chatsession",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="knowledgedocument",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Knowledge Document",
                "verbose_name_plural": "Knowledge Documents",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.RenameIndex(
            model_name="knowledgedocument",
            new_name="core_knowle_indexed_29f4c2_idx",
            old_name="core_knowle_indexe_created_idx",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("user", "User"),
                    ("assistant", "Assistant"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="content",
            field=models.TextField(help_text="Document content"),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="indexed_in_rag",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether document is indexed in RAG",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="metadata",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional metadata as JSON"
            ),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="Source URL of the document", null=True
            ),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="title",
            field=models.CharField(help_text="Document title", max_length=255),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="core_chatme_session_76a3ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user_profile", "is_active", "-created_at"],
                name="core_chatse_user_pr_32c931_idx",
            ),
        ),
    ]
