# Generated by Django 6.0 on 2025-12-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_chatmessage_options_alter_chatsession_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="feedback",
            field=models.IntegerField(
                blank=True, choices=[(1, "Useful"), (-1, "Not Useful")], null=True
            ),
        ),
    ]
