# Generated by Django 5.0.7 on 2024-07-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MonitoredChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text="The username of the Telegram channel (e.g., 'durov_channel').", max_length=100, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the channel was added.')),
            ],
            options={
                'verbose_name': 'Monitored Channel',
                'verbose_name_plural': 'Monitored Channels',
                'ordering': ['-added_at'],
            },
        ),
    ]


