# Generated by Django 5.0.7 on 2025-12-18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestedTelegramMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("channel_username", models.CharField(db_index=True, max_length=100)),
                ("message_id", models.BigIntegerField(db_index=True)),
                ("source_url", models.URLField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("ingested", models.BooleanField(db_index=True, default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ingestedtelegrammessage",
            index=models.Index(fields=["channel_username", "message_id"], name="monitoring_ing_chan_msg_idx"),
        ),
        migrations.AddIndex(
            model_name="ingestedtelegrammessage",
            index=models.Index(fields=["content_hash", "ingested"], name="monitoring_hash_ing_idx"),
        ),
    ]




