# Generated by Django 6.0 on 2025-12-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0003_ingestedtelegrammessage_rag_document_id"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ingestedtelegrammessage",
            new_name="monitoring__channel_a169e9_idx",
            old_name="monitoring_ing_chan_msg_idx",
        ),
        migrations.RenameIndex(
            model_name="ingestedtelegrammessage",
            new_name="monitoring__content_eececf_idx",
            old_name="monitoring_hash_ing_idx",
        ),
        migrations.AddField(
            model_name="monitoredchannel",
            name="rag_message_count",
            field=models.PositiveIntegerField(
                default=100,
                help_text="The number of recent messages to process for RAG.",
            ),
        ),
    ]
